Add support for Tenma 72-13360
kxtells/tenma-serial pull request #12
Opened 2023-05-31 12:03 UTC by norlins-scionova

Adds a Tenam_72-13360 class that controls 72-13360 PSU

This is fully backwards compatible. The main change is that 72-13360 has one channel and does not specify it in the messages.

Notes on the implementation: The goal of the current implementation was to add 72-13360 support while having minimum impact on the existing code.

The place where the current implementation gets a bit ugly is readVoltage and readCurrent as they need to take a channel argument for the feedback mechanism for setCurrent/setVoltage to work. I tried to modify the old code as little as possible but can easily for example call readCurrent() rather than readCurrent(channel) in the setCurrent function if the channel is "" if you prefer.

2023-06-28 10:57 UTC, kxtells commented
I've been the whole month a bit out, but thanks for the changeset. I will have a look at the code to confirm existing power supplies still work before merging :-)

2023-06-28 14:37 UTC, kxtells commented
You are right that existing power units will still work.

At first I was a bit confused but from your code I guessed that this power supply does not conform to the the same serial protocol we've seen so far, since `2545` also has a single channel but provides it in the serial commands.

I'm aware that those documents are iffy and usually not complete, but here we have

- [72-2545](https://www.farnell.com/datasheets/3217055.pdf)
- [72-13360](https://www.farnell.com/datasheets/3679773.pdf)

Funnily enough, for 13360 the documentation in spanish actually comes with some serial commands described [72-13360-ES](https://www.farnell.com/datasheets/2819988.pdf) so I can follow your code with some light.

And yes, we can see there's some kind of protocol change there in two parts.

1. Commands do not need to specify channel
2. Some commands now end with `:`

| 2545| 13360|
|---|---|
| ![image](https://github.com/kxtells/tenma-serial/assets/487073/fad5a783-d18c-4b60-b698-06be5a5ce093)|![image](https://github.com/kxtells/tenma-serial/assets/487073/92451858-c066-457a-8806-9500c7b78979) forget the 2nd command as it refers to a RS485
|`BEEP1`|`BEEP:1`|
| ![image](https://github.com/kxtells/tenma-serial/assets/487073/e15e0ea1-f17f-4ea1-b434-61ea6fcd6097)| ![image](https://github.com/kxtells/tenma-serial/assets/487073/d09962a3-e51c-4e34-b445-88f8154a98fe)|
| `VOUT1?`| `VOUT?` |

I want to review a bit more before merging anything. It's a bit annoying that `72-13320` follows the current serial protocol and `72-13360` goes its own way heheh.

2023-06-28 17:28 UTC, norlins-scionova commented
Yeah, it really threw me for a loop that it had a different protocol. The protocol (the paper documentation) I got with the PSU also didn't match exactly to what it took but it was close enough that I could guess the rest.

I really do not know why it is different and I agree that it is frustrating. I would be happy to answer any question and can probably find time to make changes if you want something changed and do not have time yourself.

To make the code look very nice you can make the channel an optional argument but then it would need to be moved last which means this would be a non-backwards compatible change. For adding a single PSU it did not feel reasonable but at the same time it is confusing if the function takes a channel argument which is then ignored. That is why there is so much code that  pretty much just calls "super.<function>".

2023-06-30 07:48 UTC, kxtells requested changes
After this newfound knowledge it seems your approach is more than acceptable, as you said: the least amount of changes possible to make this work.

We will have to "wait and see" for other PSUs, or directly try to ask farnell (I've never been too successful with that).

I added some comments in your PR to be addressed or discussed before we merge support for this unit.

2023-06-30 07:48 UTC, kxtells commented on tenma/tenmaDcLib.py
> +    def readCurrent(self, channel=""):
I see, we will be able to skip the `-C` in `tenma-control` accept the default of 1 and just skip it by calling super with our `""` empty string

2023-06-30 07:48 UTC, kxtells commented on tenma/tenmaDcLib.py
> +class Tenma72_13360(Tenma72_13320):
I would like a docstring here, commenting this "problematic" behavioud

2023-06-30 07:48 UTC, kxtells commented on tenma/tenmaDcLib.py
> +    def setVoltagePriority(self):
Ideally, up until now we forced all the functions to be available in `Tenma72Base` so we can freely call it in all PSUs but raise a `NotImplemented` error

2023-06-30 09:58 UTC, kxtells commented
@norlins-scionova I've been in contact with KORAD this morning (Farnell did not actually respond, and TENMAs are just rebranded Korads).

Unit 72-13360 corresponds to a korad KWC, and they just sent me the protocol for that unit, you can find it here https://drive.google.com/file/d/1NyQ8eip2xstyChzNAAmNSRBogST0yTyO/view?usp=sharing.

In the end it seems that we're just trying to map the 485 protocol (that has an address) to the previous 232 protocol (no address).

From here I think we can follow three paths.

1. Leave it as is (we provide support with your code, although as you say it's probably not the long term best)
2. Modify `Tenma72Base` to have a `protocol="RS232"` or `protocol="RS485"'. Building the command appropriately
3. Have two classes for 232 and 485

I think I'm veering to number 2 as it would be the clearer one, and we just have to specify the `protocol` for each class, + add an optional `address` parameter in all the commands. (iup, loads of code). Channel should also be optional but since it would not be backwards compatible we can go with your solution (simply send the empty string for units that need it)

In any case, I think it's better to just fix the comments from this PR and afterwards we can work on a re-organization :-)

I guess that `VSET:12` is interpreted as `set to 12 all units connected` , so if you only have 1 unit it does what we expect it to do.

2023-07-05 11:10 UTC, norlins-scionova commented on tenma/tenmaDcLib.py
> +        raise NotImplementedError("The normal saveConf and recallConf works well for " +
Sure, I will change that

2023-07-05 11:13 UTC, norlins-scionova commented
@kxtells I agree that solution number 2 seems good. I might have some time later this week or early next week to make the changes. Will update the PR (or add some comment here if I run into complications) and then we can go from there.

2023-07-14 13:26 UTC, norlins-scionova commented
@kxtells I made some changes to address your comments. I would like to not have a channel in the methods of 13360 and just having different protocols inside of the base class does not solve this unless we want to use some multimethod stuff which I think is the wrong way to go.

I think the proper way to do that would be to create a new class which contains the basic functionality of sending and receiving messages from the PSU and then let tenma72_base own that class (or inherit from it if you prefer) and also let a new class (along the lines of tenma_RS232_base) also inherit/use this class. That way tenma72_base is for the 485 protocol that uses channel and the new base class are for all PSU that use RS232 protocol.

If you instead prefer I can change the tenma13360 to take channel as an argument and just make the changes inside of tenma_base so that it either ignores or uses the channel depending on protocol. This means that all of the methods that just call super with channel "" would go away (as they are handled by the base class). The problem with that approach is that it might be non-obvious that channel does not matter for 13360 for people that want to use the Tenma72_13360 class directly and not the CLI.

2023-07-14 15:36 UTC, kxtells commented
Hi @norlins-scionova ! thanks for your efforts.

But I think we have ourselves a mismatch between the `RS232` and `RS485` protocols.

All the currently supported units use `RS232`, your unit seems to use the `RS485` protocol (from what I understand with the documents that Korad sent me). Maybe the 13320 is also on that protocol 

`RS232` aims to connect a host with a single PSU. That PSU might have multiple channels or not (for example  my unit Tenma72_2545 has a single channel, but the protocol is multichannel (for example 13320 has 3 channels).

![image](https://github.com/kxtells/tenma-serial/assets/487073/a977b42c-b83b-40ef-a3e5-7fe9e98b3cfe)
`ISET1:13` -> set Channel 1 to 13
`ISET2:13` -> set Channel 2 to 13
`ISET:13` -> Probably invalid? I never tried

`RS485` is a protocol that can connect a host with multiple PSUs in a daisy chain. Since there might be multiple `PSUs` connected we need a new `address` option so the correct PSU responds. Apparently that value can be skipped

![image](https://github.com/kxtells/tenma-serial/assets/487073/d8f40339-4464-4d5b-bd9c-b380b59ca6af)

`ISET01:13` -> set PSU with address 1 to 13
`ISET02:13` -> set PSU with address 2 to 13
`ISET:13` -> Set ALL PSUs to 13 (I assume it means that, did not try). Since this is only one PSU connected, that one is the one responding.

I think the distinction is important, although the protocols look very similar :warning: :eyes:  and surely this `tenma13360` does not handle different protocols depending if you connect the USB, the RS232 or the 485 port (I was looking for the unit online and has inputs for everything :-) )

This things work better for me with an image:
![image](https://github.com/kxtells/tenma-serial/assets/487073/cde6679b-9bf8-49ef-a3ed-fac9e53af37b)

# now what?

I agree with you, the original idea to discern between `RS232` and `RS485` might make this more difficult than expected. Totally my bad :bow: 

At that point I think the easiest approach will be to split it totally to make it manageable.
1. Leave Tenma72Base as is, alongside their child
2. Create your Tenma13360Base where you implement the commands with that protocol. About the same as Tenma72 but with the protocol that works for you. No `channel`, but optional `address`. If address is not set you just leave it blank (as we see in the examples). 
3. Crete your Tenma13360 that configures and implements (Similar to what we do with Tenma72Base and children)

I think this is the best way because the api is different as you say. `channel` is not optional, but `address` is
`setVoltage(channel, mv)` vs `setVoltage(mv, address="")`

Then, we don't care if tenma-control can work with this new unit or not. You'll probably need to modify too the `instantiate_tenma_class_from_device_response` to take it into account if you want to auto-instantiate. But in the case that you're just scripting this, probably you'll be fine by directly instantiating your model.

Let me know what you think

And thanks again :-)

2023-08-15 16:26 UTC, norlins-scionova commented
Hi,

Sorry for the long delay. I created a new Tenma72_13360Base which is not related to Tenma72Base as discussed before.

I did create a TenmaSerialHandler which contains the functions:

setPort
_sendCommand
_readBytes
_readOutput
close

Because that behavior is identical regardless of model. If you prefer I can duplicate the functions that are now in TenmaSerialHandler in Tenma72Base and Tenma_13360Base instead as right now the serialEOL is set in __init__ rather than as a constant in the class. I however think this design is slightly nicer.

Other than moving the above 5 functions out of Tenma72Base it is unchanged from before I started adding 13360.

I also do not have things for TenmaControl.py. I will let that only use Tenma72Base for now.

2023-08-30 10:42 UTC, kxtells commented
Thanks @norlins-scionova , I was on holiday so I did not see this until now. I will have a look but the way you describe the implementation sounds good for the current version.

2023-09-20 11:59 UTC, kxtells commented
OK, finally merging this. Thanks @norlins-scionova

2023-09-20 11:59 UTC, merged